### ISSUE TITLE
Document of syntax in manifest.yml

### ISSUE THREAD

**Issue by duynguyen** [AdobeDocs/project-firefly#60]
We don't have yet a complete document of the grammar in manifest.yml file. The closest is [wskdeploy docs](https://github.com/apache/openwhisk-wskdeploy/tree/master/docs) but they are not exactly the same. We should have a complete doc for this in project Firefly, tentatively part of https://github.com/AdobeDocs/project-firefly/blob/master/guides/app-hooks.md.

**Comment by duynguyen** [comment]
This is also a good inclusion: https://github.com/adobe/aio-cli/issues/207.

**Comment by sarahxxu** [comment]
Configuring action timeout in manifest

```
actions:
  generic:
    function: actions/generic/index.js
    runtime: 'nodejs:12'
    limits:
      timeout: 1800000
```
